name: Playwright Tests

on:
  push:
    branches:
      - main
      - develop

  schedule:
    - cron: '0 6 * * *' # Runs daily at 6 AM UTC

  workflow_dispatch:
    inputs:
      test_type:
        description: 'Choose test type (api, ui, all)'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - api
          - ui

jobs:
  tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [all]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          if [ "${{ github.event.inputs.test_type }}" == "api" ]; then
            npx playwright test --project=api
          elif [ "${{ github.event.inputs.test_type }}" == "ui" ]; then
            npx playwright test --project=chromium
          else
            npx playwright test
          fi

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always() # Always upload even if tests fail
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
